### ISSUE TITLE
Argument 1 of Window.getComputedStyle does not implement interface Element.

### ISSUE THREAD

**Issue by Jnull** [lukecfairchild/FB-Cleanup#2]
need to put a check to make sure the first argument of getComputedStyle is an interface Element. 
getComputedStyle function is used 14 times currently. 

sponsoredPosts is causing this on the 'messages' and the 'edit profile' links.

**Comment by Jnull** [comment]
on those pages we have to find new rules: 

the parents do not have borderStyle(s): 
```
borderLeftColor:"rgb(233, 234, 237)"
borderLeftStyle:"none"
```

**Comment by lukecfairchild** [comment]
What is happening? Is it not removing the sponsored posts?

**Comment by Jnull** [comment]
Nothing is happening on "Messages" and "Edit Profile", 

JavaScript Error: TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.  sponsoredPosts function is causing it.

**Comment by lukecfairchild** [comment]
The only time that error would happen I think is if what is passed into it is not a actual element on the page.

**Comment by Jnull** [comment]
well, it will return null because there is no parent element with borderLeftStyle:"bold"

**Comment by Jnull** [comment]
FIXED. :+1:

**Comment by Cristocarl** [comment]
could someone help me to fix this,
Here is my error, i already did upgrading mozilla browser form 50.0.1 to 52.02

[error] locator not found: //a[@class="direct-to-page"], error = TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.

**Comment by Jnull** [comment]
This seems to be a new problem, lets open a brand new bug/issue instead of an old one: #7 
Could u explain how to reproduce the error in #7 ? 

I havent touched the code in awhile Luke but i'll help if i can?
